{% set name = "coloraide" %}
{% set version = "4.1" %}
{% set sha256 = "8c57823227ba941f60a2d59b46cc023d6d3e4c6ae065117e40717391569e9f7d" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coloraide-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: {{ build_number }}

requirements:
  host:
    - python >=3.8
    - hatchling >=0.21.1
    - pip
  run:
    - python >=3.8

test:
  imports:
    - coloraide
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/coloraide/
  summary: A color library for Python.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://facelessuser.github.io/coloraide/
  dev_url: https://github.com/facelessuser/coloraide

extra:
  recipe-maintainers:
    - seantycho
    - mfisher87
    - rushirajnenuji
