{% set name = "coloraide" %}
{% set version = "3.3.1" %}
{% set sha256 = "bb945bc61aa08ac0927fdaec5a1052a8b30e64e5e31c4c94f1e706a7617297d8" %}
{% set build_number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coloraide-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: {{ build_number }}

requirements:
  host:
    - python >=3.8
    - hatchling >=0.21.1
    - pip
    - python >=3.6
    - hatchling 
  run:
    - python >=3.8

test:
  imports:
    - coloraide
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/coloraide/
  summary: A color library for Python.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://facelessuser.github.io/coloraide/
  dev_url: https://github.com/facelessuser/coloraide

extra:
  recipe-maintainers:
    - seantycho
    - mfisher87
    - rushirajnenuji
